/*++

Module Name:

    device.c - Device handling events for example driver.

Abstract:

   This file contains the device entry points and callbacks.

Environment:

    Kernel-mode Driver Framework

--*/

#include <ntifs.h>
#include "driver.h"
#include "device.tmh"

#ifdef ALLOC_PRAGMA
#pragma alloc_text (PAGE, xusbfixerCreateDevice)
#pragma alloc_text (PAGE, xusbfixerEvtDeviceContextCleanup)
#endif

NTSTATUS
xusbfixerCreateDevice(
    _Inout_ PWDFDEVICE_INIT DeviceInit
)
/*++

Routine Description:

    Worker routine called to create a device and its software resources.

Arguments:

    DeviceInit - Pointer to an opaque init structure. Memory for this
                    structure will be freed by the framework when the WdfDeviceCreate
                    succeeds. So don't access the structure after that point.

Return Value:

    NTSTATUS

--*/
{
    WDF_OBJECT_ATTRIBUTES deviceAttributes;
    PDEVICE_CONTEXT deviceContext;
    WDFDEVICE device;
    NTSTATUS status;

    PAGED_CODE();

    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&deviceAttributes, DEVICE_CONTEXT);

    deviceAttributes.EvtCleanupCallback = xusbfixerEvtDeviceContextCleanup;

    status = WdfDeviceCreate(&DeviceInit, &deviceAttributes, &device);

    if (NT_SUCCESS(status)) {
        //
        // Get a pointer to the device context structure that we just associated
        // with the device object. We define this structure in the device.h
        // header file. DeviceGetContext is an inline function generated by
        // using the WDF_DECLARE_CONTEXT_TYPE_WITH_NAME macro in device.h.
        // This function will do the type checking and return the device context.
        // If you pass a wrong object handle it will return NULL and assert if
        // run under framework verifier mode.
        //
        deviceContext = DeviceGetContext(device);

        //
        // Initialize the context.
        //
        DECLARE_CONST_UNICODE_STRING(xusb22DriverName, L"\\Driver\\xusb22");
        PDEVICE_OBJECT thisDeviceObject = WdfDeviceWdmGetDeviceObject(device);
        PUNICODE_STRING xusbfixerDriverName = &thisDeviceObject->DriverObject->DriverName;

        WDFIOTARGET target = WdfDeviceGetIoTarget(device);
        PDEVICE_OBJECT targetDevObj = WdfIoTargetWdmGetTargetDeviceObject(target);
        PDEVICE_OBJECT devObjToDereference = NULL;

        deviceContext->Upper = FALSE;

        while (targetDevObj) {
            PDRIVER_OBJECT driverObj = targetDevObj->DriverObject;

            TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DEVICE,
                        "%!FUNC! target driver name %wZ DeviceType %lx",
                        &driverObj->DriverName, targetDevObj->DeviceType);

            if (RtlEqualUnicodeString(&driverObj->DriverName, &xusb22DriverName, TRUE)) {
                TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DEVICE, "%!FUNC! xusb22 found");
                deviceContext->Upper = TRUE;
            }
            else if (RtlEqualUnicodeString(&driverObj->DriverName, xusbfixerDriverName, TRUE)) {
                TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DEVICE, "%!FUNC! lower filter found");
                deviceContext->Upper = TRUE;
                deviceContext->LowerDeviceObject = targetDevObj;
                break;
            }

            targetDevObj = IoGetLowerDeviceObject(targetDevObj);
            if (devObjToDereference) {
                ObDereferenceObject(devObjToDereference);
            }
            devObjToDereference = targetDevObj;
        }

        //
        // Initialize the I/O Package and any Queues
        //
        status = xusbfixerQueueInitialize(device);
    }

    return status;
}

VOID
xusbfixerEvtDeviceContextCleanup(
    _In_ WDFOBJECT Device
)
{
    PDEVICE_CONTEXT deviceContext;

    PAGED_CODE();

    TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DEVICE, "%!FUNC! Entry Device 0x%p", Device);

    deviceContext = DeviceGetContext(Device);

    TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DEVICE, "%!FUNC! context with input queue 0x%p",
                deviceContext->InputWaitQueue);

    if (deviceContext->Upper && deviceContext->LowerDeviceObject) {
        ObDereferenceObject(deviceContext->LowerDeviceObject);
        deviceContext->LowerDeviceObject = NULL;
    }
    else if (!deviceContext->Upper && deviceContext->InputWaitQueue) {
        WdfObjectDereference(deviceContext->InputWaitQueue);
        deviceContext->InputWaitQueue = NULL;
    }

    TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DEVICE, "%!FUNC! Exit");
}
